### ISSUE TITLE
Could not load type 'NP.Ava.Visuals.Behaviors.OverlayWindowBehavior

### ISSUE THREAD

**Issue by henrrymoraes83** [npolyak/NP.Ava.Visuals#3]
After upgrade from 1.0.33.0 to 1.0.34.0 or latest, it shows this error message:

System.TypeLoadException: 'Could not load type 'NP.Ava.Visuals.Behaviors.OverlayWindowBehavior' from assembly 'NP.Ava.Visuals, Version=1.0.34.0, Culture=neutral, PublicKeyToken=null'.'

Thank you so much!!

**Comment by npolyak** [comment]
I renamed OverlayWindowBehavior to OverlayBehavior

**Comment by henrrymoraes83** [comment]
Excellent work!! Thanks

**Comment by henrrymoraes83** [comment]
It was fixed after upgrade to UniDock 1.0.16.
